### PR TITLE
Updates to styling and adding custom confirm dialog

### PR DESCRIPTION
**Pull request by crispytoast7**
Added some better styling in the CSS file and added a custom confirm dialog. Will continue to update the CSS and fix some small things.

### CODE REVIEW

**Review by py660 — CHANGES_REQUESTED** [review]
Screenshot 2023-12-26 at 10 44 50 PM
there's just some random bar; I'm too tired rn will work on it tmr, but maybe try to fix it ig? IDK what I'm supposed to say in this PR review thing.

EDIT: btw you should await the confirm box, otherwise window.playlist won't be guaranteed to be defined to load when i click "load song index".

**Comment by crispytoast7** [comment]
@py660 Just fixed the little naughty line :)

**Comment by py660** [comment]
> @DarkOutcast6 is attempting to deploy a commit to the **J's projects** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=J's%20projects&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%220feeb39b6fe3b57643d0d341f02e2db10e1039ad%22%7D%2C%22id%22%3A%22QmfGbdtFgfTfLudKxnzJJuLVEXtsmrBfdw4VMVq1nqpY1Y%22%2C%22org%22%3A%22py660%22%2C%22prId%22%3A2%2C%22repo%22%3A%22MusiGuesser%22%7D).

AAARRRGGGHHHH NOT THIS AGAIN, VERCEL!

**Comment by py660** [comment]
Ok, I'll go through the diff and approve applicable changes.
bc github pr checkout made me confused and the online diff editor sucks.

**Comment by py660** [comment]
how do i merge? This is so annoying idk how to merge; i'll just try to commit to darkoutcast6 branch ig. (and then edit it into main hopefully? how do i do it lol)

**Comment by py660** [comment]
aaaaaaaaaa how to reopen this?

**Comment by crispytoast7** [comment]
Wait why do you need to re open it?

**Comment by py660** [comment]
i realized that i could have just done a git diff with multiple origins, but nvm that might actually be too difficult.... git is so confusing when it comes to PRs

**Comment by crispytoast7** [comment]
Lol ikr. Have you added it yet?

**Comment by py660** [comment]
I'm currently battling with ClouDNS's annoying service, so expect it to be committed in a few days... (unless i realize that i procrastinate too much and start grinding through PR).

**Comment by crispytoast7** [comment]
Oof, hope it works out lol

**Comment by crispytoast7** [comment]
@py660 Any luck deploying it?

**Comment by py660** [comment]
I'm dealing w/ school stuff rn, but progress is approximately at 90%:

Screenshot 2024-01-07 at 12 30 11 AM

(trying to balance your code with SaladShooter... saladshooter has nice css, but your functionality is also very cool.)

**Comment by py660** [comment]
Sorry that I'm not updating this, I've found myself waist-level deep in personal matters (such as competitions, school, etc)... I'll get to it soon :(

**Pull request merged**
